import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable";
import SideBar from "@/components/SideBar/SideBar";
import { ScrollArea } from "@/components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans text-base">
      <body className={inter.className}>
        <ResizablePanelGroup direction="horizontal">
          <ResizablePanel defaultSize={20} maxSize={20} minSize={15}>
            <SideBar />
          </ResizablePanel>
          <ResizableHandle withHandle />
          <ResizablePanel defaultSize={80}>
            <ScrollArea >
              {children}
            </ScrollArea>
          </ResizablePanel>
        </ResizablePanelGroup>
      </body>
    </html>
  );
}
