import "@/app/globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen justify-center items-center flex">
        {children}
        <Toaster />
      </body>
    </html>
  )
}
